--- 
# --extra-vars "deployment=blue|green"
- name: "blue deployment"
  hosts: tag_aws_cloudformation_logical_id_WebServerGroupBlue
  user: ec2-user
  become: yes

  tasks: 
    - ping: 

    - git:
        repo: 'https://github.com/ericstrongDevOps/SimpleWebPage.git'
        dest: /var/www/html/deployment
        version: blue

