--- 
- 
  hosts: servers
  tasks: 
    - 
      copy: "src={{ file }} dest=/home/bitnami/htdocs/"
      name: "Copy File"
    - 
      name: "Create User"
      user: "name=eric groups=adm shell=/bin/bash,sudo generate_ssh_key=yes"
    - 
      name: "Install {{ package }}"
      apt: "name={{ package }} state=latest"
  vars: 
    package: git
    file: index.html